# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
tab_title: "Alan's Website"
title: "Alan Ma: Data(rt)"
email: alanma0907@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  Data is only as meaningful as the subject deems.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://wolfier.github.io" # the base hostname & protocol for your site
github_username: wolfier
linkedin_username: alanmaut

# Build settings
markdown: kramdown
theme: minima

# Google Analytics Key
google_analytics: UA-83242184-1

#page structure
include: ["_pages"]
permalink: /:title/